#!/bin/bash
SCRIPT_DIR="$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd
)" # Figure out where the script is running

case $(uname -sm) in
'Linux x86_64')
    os='linux-x86_64'
    ;;
'Darwin x86' | 'Darwin x86_64' | 'Darwin arm64')
    os='osx'
    ;;
'Windows')
    os='win32'
    ;;
esac

denor="deno run -A --unstable"
denot="deno test -A --unstable"

case "$1" in
#CMD - get_pact_ffi
get_pact_ffi)
    $denor pact/downloadFfi.ts --run
    ;;
#CMD - get_pact_plugin_cli
get_pact_plugin_cli)
    curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-plugins/main/scripts/install-plugin-cli.sh | bash
    ;;
#CMD - get_protobuf_plugin
get_protobuf_plugin)
    pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
    ;;
#CMD - test_grpc_area_client
test_grpc_area_client)
    $denot pact/usage/areaCalculatorClientTest.ts
    ;;
#CMD - test_grpc_greeter_client
test_grpc_greeter_client)
    $denot pact/usage/greeterClientTest.ts
    ;;
#CMD - run_area_calculator
run_area_calculator)
    $denor pact/usage/areaCalculator/areaCalculatorServer.ts & _pid=$!;
    sleep 3 && $denor pact/usage/areaCalculator/areaCalculatorClient.ts --run ;kill $_pid
    ;;
#CMD - run_grpc_greeter
run_grpc_greeter)
    $denor pact/usage/greeter/greeterServer.ts & _pid=$!;
    sleep 3 && $denor pact/usage/greeter/greeterClient.ts --run ;kill $_pid
    ;;
#CMD - run_product_api_provider
run_product_api_provider)
    $denor pact/usage/productApi/provider/server.ts
    ;;
#CMD - run_product_api_provider
test_product_api_provider)
    $denot pact/usage/productApi/provider/product/product.test.ts
    ;;
#CMD - act
act)
    act --container-architecture linux/amd64
    ;;
#CMD - all
all)
    ./run test_grpc_area_client
    ./run test_grpc_greeter_client
    ./run run_area_calculator
    ./run run_grpc_greeter
    ;;
* | help)
    echo "available commands"
    echo "______"
    cat ./run | grep '#CMD' | awk  '{print $3}'
    ;;
esac
