name: Build

on:
  push:
  workflow_dispatch:

jobs:
  deno:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - if: runner.os == 'Windows'
        run: rm 'C:\Windows\System32\bash.exe'
      - if: runner.os == 'macOS'
        run: brew install protobuf
      - if: runner.os == 'Windows'
        name: Choco install protoc
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install protoc
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: ./run get_pact_ffi
      - run: ./run get_pact_plugin_cli
      - run: /root/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
      - run: ./run test_grpc_area_client
      - run: ./run test_grpc_greeter_client
      - run: ./run run_area_calculator
      - run: ./run run_grpc_greeter
